# Generated by Django 4.2.7 on 2023-11-09 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_doctors_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.TextField()),
                ('Number', models.TextField()),
                ('Zip_code', models.TextField()),
                ('City', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Surname',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
