# Generated by Django 4.2.7 on 2023-11-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_name_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Documentation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.documentation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Surname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Surname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
