# Generated by Django 4.2.7 on 2023-11-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient_documentation_alter_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
