# Generated by Django 4.2.7 on 2023-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_documentation_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='property',
            field=models.CharField(default='', max_length=50),
        ),
    ]
