# Generated by Django 4.2.7 on 2023-11-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_patient_documentation_documentation_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='patients',
        ),
    ]
