# Generated by Django 4.2.7 on 2023-11-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_documentation_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Documentation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.documentation'),
        ),
    ]
