# Generated by Django 4.2.7 on 2023-11-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_patient_documentation_documentation_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='visits',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
