# Generated by Django 4.2.7 on 2023-12-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
