# Generated by Django 4.2.7 on 2023-11-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
    ]
