# Generated by Django 4.2.7 on 2023-11-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DateOfBirth',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
