# Generated by Django 4.2.7 on 2023-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
