# Generated by Django 4.2.7 on 2023-12-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_city_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='date_of_birth',
        ),
    ]
