# Generated by Django 4.2.7 on 2023-12-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_patient_address_patient_name_patient_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Zip_code',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Surname',
            new_name='surname',
        ),
    ]
