# Generated by Django 4.2.7 on 2023-12-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_medicine_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diseases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.AddField(
            model_name='visit',
            name='medicines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicine'),
        ),
    ]
