# Generated by Django 4.2.7 on 2023-12-10 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_medicine_dosage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='documentation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.documentation'),
        ),
    ]
