# Generated by Django 4.2.7 on 2023-12-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_dateofbirth_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
