# Generated by Django 4.2.7 on 2023-12-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_documentation_patients_patient_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='visits',
        ),
        migrations.AddField(
            model_name='disease',
            name='documentation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.documentation'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='documentation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.documentation'),
        ),
        migrations.AddField(
            model_name='visit',
            name='documentation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.documentation'),
        ),
    ]
