# Generated by Django 4.2.7 on 2023-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_visit_doctor_alter_visit_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='medicines',
        ),
        migrations.AddField(
            model_name='visit',
            name='diseases',
            field=models.ManyToManyField(blank=True, null=True, to='main.disease'),
        ),
        migrations.AddField(
            model_name='visit',
            name='medicines',
            field=models.ManyToManyField(blank=True, null=True, to='main.medicine'),
        ),
    ]
