# Generated by Django 4.2.7 on 2023-12-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_visit_diseases_remove_visit_medicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='main.medicine'),
        ),
    ]
