# Generated by Django 4.2.7 on 2023-12-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_visit_diseases_alter_visit_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='medicines',
        ),
        migrations.AddField(
            model_name='disease',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.visit'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.visit'),
        ),
    ]
