# Generated by Django 4.2.7 on 2023-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_visit_diseases_remove_visit_medicines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
