# Generated by Django 4.2.7 on 2023-12-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_disease_date_medicine_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='date',
        ),
    ]
