# Generated by Django 4.2.7 on 2023-12-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_disease_date_remove_medicine_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease'),
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2000-01-01')),
                ('end_date', models.DateField(default='2000-01-01')),
                ('description', models.CharField(default='', max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='medicine_dosage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dosage'),
        ),
    ]
