# Generated by Django 4.2.7 on 2023-12-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_disease_visit_remove_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='property',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
