# Generated by Django 4.2.7 on 2023-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_visit_notes_alter_medicine_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='description',
            field=models.CharField(default='', max_length=25),
        ),
    ]
