# Generated by Django 4.2.7 on 2024-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
