# Generated by Django 4.2.7 on 2024-01-08 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_disease_symptoms_alter_visit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='medicine_dosage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dosage'),
        ),
    ]
