# Generated by Django 4.2.7 on 2024-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
