# Generated by Django 4.2.7 on 2024-01-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_visit_medicine_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='disease',
            field=models.ForeignKey(default='default', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.patient'),
        ),
    ]
