# Generated by Django 4.2.7 on 2024-01-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_visit_disease_alter_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='medicine',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.medicine'),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='patient',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.patient'),
        ),
    ]
