# Generated by Django 4.2.7 on 2024-01-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_dosage_medicine_alter_dosage_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.medicine'),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.disease'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patient'),
        ),
    ]
